import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const menuItems = [
    {
        title: "Home",
        url: "/",
        sec: 0,
        onlyUnauth: false,
        submenu: [],
    },
    {
        title: "Raffles",
        url: "#",
        sec: 1,
        onlyUnauth: false,
        submenu: [
            {
                title: "Create",
                url: "/create-raffle",
                sec: 2,
                onlyUnauth: false,
            },
            {
                title: "My Raffles",
                url: "/my-raffles",
                sec: 2,
                onlyUnauth: false,
            },
            {
                title: "Joined Raffles",
                url: "/joined",
                sec: 1,
                onlyUnauth: false,
            },
        ],
    },
    {
        title: "Poaps",
        url: "#",
        sec: 1,
        onlyUnauth: false,
        submenu: [
            {
                title: "Inventory",
                url: "/poap",
                sec: 1,
                onlyUnauth: false,
            },
            {
                title: "Create",
                url: "/create-event",
                sec: 2,
                onlyUnauth: false,
            },
            {
                title: "Drop",
                url: "/create-drop",
                sec: 2,
                onlyUnauth: false,
            },
            {
                title: "Created Poaps",
                url: "/list-events",
                sec: 2,
                onlyUnauth: false,
            },
        ],
    },
    {
        title: "Profile",
        url: "/profile",
        sec: 1,
        onlyUnauth: false,
        submenu: [],
    },
    {
        title: "auth",
        url: "#",
        onlyUnauth: false,
        sec: 0,
        submenu: [],
    },
];

type NavBarProps = {
    title: string;
    url: string;
    sec: number;
    onlyUnauth: boolean;
    submenu: Array<Object>;
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav className={`hidden md:block`}>
                    <ul className={`flex items-center flex-wrap`}>
                        {menuItems.map((item) => {
                            return (
                                <li key={item.title} className={`relative hover:bg-white group`}>
                                    {/* <Link href={item.url}>{item.title}</Link> */}
                                    {item.title}
                                    <Menu {...item} />
                                </li>
                            );
                        })}
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    );
}
const toggleModal = () => {};
const reqSign = () => {};
const connected = false;

const Menu = ({ title, url, sec, onlyUnauth, submenu }: NavBarProps, authState: number) => {
    if (authState === 0 && onlyUnauth) {
        return (
            <>
                <button onClick={toggleModal}> Register </button>
                {connected && <button onClick={reqSign}> Sign In </button>}
            </>
        );
    }
    if (authState >= sec) {
        return <span className="menu ">{title}</span>;
    } else {
        return <></>;
    }
};
